version: "2"
services:

  zookeeper1:
    container_name: zookeeper1
    image: znly/zookeeper:v3.4.8
    environment:
      - ZOO_ID=1
      - ZOO_SERVERS=zookeeper1,zookeeper2,zookeeper3

  zookeeper2:
    container_name: zookeeper2
    image: znly/zookeeper:v3.4.8
    environment:
      - ZOO_ID=2
      - ZOO_SERVERS=zookeeper1,zookeeper2,zookeeper3

  zookeeper3:
    container_name: zookeeper3
    image: znly/zookeeper:v3.4.8
    environment:
      - ZOO_ID=3
      - ZOO_SERVERS=zookeeper1,zookeeper2,zookeeper3

